
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hhe80
 */
public class Patient_Release extends javax.swing.JFrame {

    /**
     * Creates new form Patient_Bil
     */
    public Patient_Release() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rel_date = new javax.swing.JTextField();
        Patient_Id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable30 = new javax.swing.JTable();
        Show_Table = new javax.swing.JButton();
        In_PatientAdd1 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Healt_CheckUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Release");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Release_Date");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Patient ID");

        rel_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_dateActionPerformed(evt);
            }
        });

        Patient_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_IdActionPerformed(evt);
            }
        });

        jTable30.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill_ID", "Patient_ID", "Patient_Name", "Release_Date", "Admission Date", "No_Of_Dayes"
            }
        ));
        jScrollPane1.setViewportView(jTable30);

        Show_Table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Show_Table.setText("Release_Patient");
        Show_Table.setToolTipText("");
        Show_Table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_TableActionPerformed(evt);
            }
        });

        In_PatientAdd1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        In_PatientAdd1.setText("Add");
        In_PatientAdd1.setToolTipText("");
        In_PatientAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                In_PatientAdd1ActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Healt_CheckUp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Healt_CheckUp.setText("Generate Bill");
        Healt_CheckUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Healt_CheckUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Show_Table, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Patient_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rel_date, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 173, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(In_PatientAdd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Healt_CheckUp)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Patient_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rel_date, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back)
                        .addGap(18, 18, 18)
                        .addComponent(In_PatientAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Healt_CheckUp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Show_Table, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rel_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rel_dateActionPerformed

    private void Patient_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_IdActionPerformed

    private void Show_TableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_TableActionPerformed

         
        DefaultTableModel model = (DefaultTableModel) jTable30.getModel();
            model.setRowCount(0);
        
          try{
              
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
   
   
 
       Statement st = connection.createStatement();
       String sql = "select Bill.BillID,Bill.PatientID,Patient.Patient_Name,Bill.Release_Date,Lab.Admission_Date,DATEDIFF(day,Lab.Admission_Date,Bill.Release_Date) As N0_Of_Dayes from Bill join Lab on Bill.PatientID = Lab.PatientID join Patient on Patient.PatientID = Lab.PatientID  join Lab_Report on Lab_Report.PatientID = patient.PatientID where Lab_Report.Patient_Category='In'";
       
       ResultSet rs = st.executeQuery(sql);
           
       while(rs.next()){
           
           String Bill_Id = String.valueOf(rs.getString("BillID"));
           String P_Id = String.valueOf(rs.getString("PatientID"));
           String P_Name= String.valueOf(rs.getString("Patient_Name"));           
           String R_Date = String.valueOf(rs.getString("Release_Date"));
           String A_Date =  String.valueOf(rs.getString("Admission_Date"));
           String Total_Days = String.valueOf(rs.getString("N0_Of_Dayes"));
           
              
          
           String tbData[] = {Bill_Id ,P_Id,P_Name,R_Date,  A_Date,Total_Days};
           
           DefaultTableModel tblModel = (DefaultTableModel)jTable30.getModel();
           
           tblModel.addRow(tbData);
           
       }
       
       
        
        } catch (Exception e) {
            
            e.printStackTrace();
            
        }
        
                      
        
        
        
    }//GEN-LAST:event_Show_TableActionPerformed

    private void In_PatientAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_In_PatientAdd1ActionPerformed
        // TODO add your handling code here:
        
        
              String P_Id = Patient_Id.getText();
              String Rel_Date = rel_date.getText();
             
                 
               try {
              
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
   
   
         
             
         String  sqlquery = "INSERT INTO Bill(Release_Date,PatientID) VALUES ('"+Rel_Date+"','"+P_Id+"')";
         
         PreparedStatement pst = connection.prepareStatement(sqlquery);
        
         pst.execute();
         JOptionPane.showMessageDialog(null, "Registration Complete");
        
      
        
         
        
       ////////////////Clear The Text Field
       
        Patient_Id.setText("");
        rel_date.setText("");
       
       
       
        
             
       
        } catch (Exception e) {
            e.printStackTrace();
        }  
                     
              
             
         
        
        
    }//GEN-LAST:event_In_PatientAdd1ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.hide();
        new Admin().show();
    }//GEN-LAST:event_BackActionPerformed

    private void Healt_CheckUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Healt_CheckUpActionPerformed
        // TODO add your handling code here:
        this.hide();
        new Admitted_Patient_Bill().show();

    }//GEN-LAST:event_Healt_CheckUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_Release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_Release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_Release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_Release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_Release().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Healt_CheckUp;
    private javax.swing.JButton In_PatientAdd1;
    private javax.swing.JTextField Patient_Id;
    private javax.swing.JButton Show_Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable30;
    private javax.swing.JTextField rel_date;
    // End of variables declaration//GEN-END:variables
}
